### ISSUE TITLE
Can't generate sourcemaps on Win8.1 x64

### ISSUE THREAD

**Issue by brakmic** [evs-chris/gobble-concat-css#1]
Hi,

When the option "sourcemap" is set to true the following error appears:

``` bash
ENOENT, open 'd:\src\js\ractive\RactAmp\.gobble\05-merge\1\assets\assets\bundle.css.map *'
>>>
Error: ENOENT, open 'd:\src\js\ractive\RactAmp\.gobble\05-merge\1\assets\assets\bundle.css.map *'
    at Error (native)
```

Interestingly, the _CSS base path_ is wrong because in my gobblefile.js I have **'./assets/bundle.css'** and not **'./assets/assets/bundle.css'**.

Anyway, here's my gobblefile.js too:

``` javascript
var gobble = require('gobble');

module.exports = gobble([
              //document root
              gobble('./src/root'),
              //transform styles
              gobble('./src/styles').transform('concat-css',
              {
                  debug: true,
                  dest: './assets/bundle.css',
                  sourcemap: true,
              }),
              //transform scripts
              gobble('./src/scripts')
              .transform('ractive',
              {
                  type: 'es6'
              })
              .transform('babel',
              {
                  optional: ['runtime'],
                  sourceMap: true,
                  compact: true,
                  nonStandard: true
              })
              .transform('browserify', {
                  entries: './advarics/app.js',
                  dest: './bundle.js',
                  sourcemap: true
              }),
              ]
              );
```

**Comment by evs-chris** [comment]
Yep, there was a relative path derp in the sourceMappingURL comment. I fixed that and attempted to make the sourcemap comment more flattening friendly, but I'm not sure how well that part worked out. It switches to the `//#` comment style from the more css familiar `/*# */` style, and I'm not sure if that will have other implications. If you have the time, give 0.0.3 a go and see if it works for you.

**Comment by brakmic** [comment]
Hi,

It works now and generates a _bundle.css_ with proper sourceMappingURL in it.

Many thanks. :+1:
